import React, { useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import { Search, Calendar, User, ArrowLeft, Scale } from 'lucide-react';
import { ResearchCard } from '../components/common/ResearchCard';
import { SEO } from '../components/common/SEO';

const RESEARCH_INDEX_SCHEMA = {
  "@context": "https://schema.org",
  "@type": "CollectionPage",
  "name": "Commercial Real Estate Research Desk & Educational Papers | Joint Bricks",
  "description": "Institutional research papers and educational guides on SPV structures, commercial retail catchments, and REIT vs SM-REIT comparisons. Joint Bricks Research Desk.",
  "url": "https://jointbricks.com/research"
};

export const ResourcesPage: React.FC = () => {
  const { slug } = useParams<{ slug?: string }>();
  const [selectedCategory, setSelectedCategory] = useState<string>('All');
  const [searchQuery, setSearchQuery] = useState<string>('');

  const articles = [
    {
      slug: "understanding-spv-real-estate-investment",
      title: "Understanding SPV-Based Real Estate Investment",
      excerpt: "How dedicated private limited companies isolate commercial property title while enabling fractional equity shareholding under Indian corporate law.",
      category: "Investment Education",
      readTime: "6 min read",
      date: "[DATE — TO BE PROVIDED]",
      author: "Joint Bricks Research Desk",
      imageUrl: "/images/commercial-retail-facade.jpg",
      content: `Special Purpose Vehicles (SPVs) are standard private limited corporate entities established for a dedicated, singular business objective — in this context, acquiring, holding, and managing a single commercial real-estate asset.

When individual investors participate in a commercial real-estate transaction, direct title ownership of a physical building creates immense legal and administrative friction. Property conveyance deeds, joint undivided ownership disputes, stamp duty re-registration, and municipal tax reassessment become unmanageable with multiple participants.

The SPV structure resolves this friction cleanly:
1. The SPV (a Private Limited Company under the Companies Act 2013) acquires and holds registered legal title to the real estate deed.
2. Investors contribute capital to the SPV and receive registered equity shares proportional to their contribution.
3. Net rental income generated by the tenant flows directly into the SPV bank account and is distributed pro-rata to shareholders.
4. On eventual property sale, net exit proceeds flow to the SPV and are distributed to shareholders after taxes and deductions.

Investors hold registered shares in the property-specific SPV, not direct title deeds to physical real estate.`
    },
    {
      slug: "what-makes-retail-property-investment-grade",
      title: "What Makes a Commercial Retail Property Investment-Grade",
      excerpt: "Evaluating high-street catchment density, footfall indices, retail frontage, and long-term lease commitment structures in commercial retail.",
      category: "Commercial Retail",
      readTime: "7 min read",
      date: "[DATE — TO BE PROVIDED]",
      author: "Joint Bricks Research Desk",
      imageUrl: "/images/urban-commercial-corridor.jpg",
      content: `Commercial retail real estate — specifically high-street retail shops and ground-floor anchor commercial units — exhibits distinct cash-flow characteristics compared to traditional office parks or residential apartments.

Key criteria for evaluating commercial retail properties:
- Catchment Density: Surrounding residential population density driving daily organic consumer footfall.
- Lease Tenure & Commitments: Long-term tenancy agreements with multi-year initial lease commitments.
- Rent Escalation: Periodic rent escalations (typically 15% every 3 years) providing contractual cash-flow growth.
- Pre-Leased Status: Sourcing properties with established, operating corporate tenants at acquisition to mitigate immediate vacancy risk.
- High-Street Visibility: Broad storefront visibility and pedestrian accessibility that preserves long-term tenant demand.`
    },
    {
      slug: "reit-vs-sm-reit-vs-spv-fractional-ownership",
      title: "REIT vs. SM-REIT vs. SPV-Based Fractional Ownership: A Comparison",
      excerpt: "An educational framework comparing public REITs, Small & Medium REITs (SM-REITs), and private SPV fractional shareholding.",
      category: "REIT/SM-REIT Education",
      readTime: "8 min read",
      date: "[DATE — TO BE PROVIDED]",
      author: "Joint Bricks Research Desk",
      imageUrl: "/images/hero-architecture.jpg",
      isReitEdu: true,
      content: `Real-estate investment vehicles in India exist across multiple regulatory and corporate frameworks:

1. Public REITs:
Large-scale pooled real-estate investment trusts registered with SEBI. These typically hold massive portfolios of Grade-A office parks valued in thousands of crores, and their units trade publicly on stock exchanges with daily price volatility.

2. Small & Medium REITs (SM-REITs):
A specialized regulatory framework introduced by SEBI for micro-market real-estate pooling, requiring specific minimum asset sizes, trustee governance, and formal SEBI registration.

3. SPV-Based Fractional Ownership (Joint Bricks Model):
Private limited SPV structures where investors hold proportional equity shareholding in a property-specific company under the Companies Act 2013. The SPV owns the single underlying real estate asset.

Regulatory Reminder: Joint Bricks is not an SM-REIT. Certain aspects of its business model may be similar to functions within an SM-REIT framework, but these similarities do not constitute SM-REIT registration or SEBI-regulated status. Joint Bricks is not currently operating as a SEBI-registered SM-REIT.`
    }
  ];

  // If viewing single article
  if (slug) {
    const article = articles.find(a => a.slug === slug) || articles[0];
    return (
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-10">
        <SEO
          title={`${article.title} | Joint Bricks Research`}
          description={article.excerpt}
          canonicalUrl={`https://jointbricks.com/research/${article.slug}`}
        />
        
        <Link
          to="/research"
          className="inline-flex items-center gap-2 text-xs font-mono font-semibold uppercase tracking-wider text-[#827E74] hover:text-[#0F0F0E] transition-colors"
        >
          <ArrowLeft className="w-4 h-4 text-[#BFA272]" />
          <span>Return to Research Desk</span>
        </Link>

        {/* Article Header */}
        <div className="bg-[#0B0B0A] text-[#FAF8F5] border border-[#23221E] rounded-xs p-8 sm:p-12 space-y-6 relative corner-crosshair">
          <div className="flex flex-wrap items-center gap-2">
            <span className="bg-[#BFA272]/20 text-[#D4BA8C] border border-[#BFA272]/40 text-[9px] font-mono font-medium px-2.5 py-0.5 rounded-xs uppercase tracking-wider">
              {article.category}
            </span>
            <span className="text-[10px] font-mono text-[#827E74]">
              {article.readTime}
            </span>
          </div>

          <h1 className="font-serif-display text-3xl sm:text-5xl font-light text-[#FAF8F5] leading-tight">
            {article.title}
          </h1>

          <div className="flex flex-wrap items-center gap-4 text-xs font-mono text-[#827E74] border-t border-[#23221E] pt-4">
            <div className="flex items-center gap-1.5">
              <User className="w-3.5 h-3.5 text-[#BFA272]" />
              <span>{article.author}</span>
            </div>
            <div className="flex items-center gap-1.5">
              <Calendar className="w-3.5 h-3.5 text-[#BFA272]" />
              <span>{article.date}</span>
            </div>
          </div>
        </div>

        {/* Article Body */}
        <div className="bg-[#FAF8F5] border border-[#DDD5C5] rounded-xs p-8 sm:p-12 space-y-6 text-sm text-[#47453F] leading-relaxed font-sans relative corner-crosshair">
          <div className="prose max-w-none space-y-4 whitespace-pre-line text-sm sm:text-base leading-relaxed text-[#0F0F0E]">
            {article.content}
          </div>

          {article.isReitEdu && (
            <div className="p-6 bg-[#0B0B0A] text-[#FAF8F5] border border-[#23221E] rounded-xs text-xs font-mono space-y-2 mt-8">
              <div className="flex items-center gap-2 text-[#BFA272] font-semibold">
                <Scale className="w-4 h-4" />
                <span>Statutory Regulatory Notice</span>
              </div>
              <p className="text-[#BCB8AD] leading-relaxed">
                "Joint Bricks is not an SM-REIT. Certain aspects of its business model may be similar to or related to functions within an SM-REIT framework, but these similarities do not constitute SM-REIT registration or SEBI-regulated status. Joint Bricks is not currently operating as a SEBI-registered SM-REIT and does not currently have SM-REIT registration or approval from SEBI."
              </p>
            </div>
          )}
        </div>

        {/* Next Articles */}
        <div className="pt-6 border-t border-[#DDD5C5]">
          <h3 className="font-serif-display text-2xl font-light text-[#0F0F0E] mb-6">
            Related Research Briefs
          </h3>
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            {articles.filter(a => a.slug !== article.slug).slice(0, 2).map(item => (
              <ResearchCard key={item.slug} {...item} />
            ))}
          </div>
        </div>
      </div>
    );
  }

  // Filter articles
  const filteredArticles = articles.filter(art => {
    const matchesCat = selectedCategory === 'All' || art.category === selectedCategory;
    const matchesSearch = searchQuery === '' || 
      art.title.toLowerCase().includes(searchQuery.toLowerCase()) || 
      art.excerpt.toLowerCase().includes(searchQuery.toLowerCase());
    return matchesCat && matchesSearch;
  });

  return (
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-12 space-y-12">
      <SEO
        title="Commercial Real Estate Research Desk & Educational Papers | Joint Bricks"
        description="Institutional research papers and educational guides on SPV structures, commercial retail catchments, and REIT vs SM-REIT comparisons. Joint Bricks Research Desk."
        canonicalUrl="https://jointbricks.com/research"
        schema={RESEARCH_INDEX_SCHEMA}
      />
      
      {/* Research Desk Header */}
      <div className="bg-[#0B0B0A] text-[#FAF8F5] border border-[#23221E] rounded-xs p-8 sm:p-16 text-center max-w-4xl mx-auto space-y-4 relative corner-crosshair">
        <span className="text-[10px] font-mono font-medium text-[#BFA272] uppercase tracking-[0.25em] bg-[#BFA272]/15 px-3 py-1 rounded-xs border border-[#BFA272]/30 inline-block">
          INTELLIGENCE & MARKET STUDIES
        </span>
        <h1 className="font-serif-display text-4xl sm:text-6xl font-light tracking-tight text-[#FAF8F5]">
          Commercial Real Estate Research Desk
        </h1>
        <p className="text-xs sm:text-sm text-[#BCB8AD] max-w-2xl mx-auto leading-relaxed">
          In-depth educational briefs on SPV capital architecture, commercial retail catchment dynamics, lease underwriting, and regulatory comparisons.
        </p>
      </div>

      {/* Filter and Search */}
      <div className="flex flex-wrap items-center justify-between gap-4 p-4 bg-[#F4F0E6] border border-[#DDD5C5] rounded-xs">
        <div className="flex flex-wrap items-center gap-2">
          {['All', 'Investment Education', 'Commercial Retail', 'REIT/SM-REIT Education'].map((cat) => (
            <button
              key={cat}
              onClick={() => setSelectedCategory(cat)}
              className={`px-3 py-1.5 text-xs font-mono uppercase tracking-wider rounded-xs transition-colors cursor-pointer ${
                selectedCategory === cat
                  ? 'bg-[#0B0B0A] text-[#FAF8F5]'
                  : 'bg-[#FAF8F5] text-[#47453F] border border-[#DDD5C5] hover:bg-[#EAE4D5]'
              }`}
            >
              {cat}
            </button>
          ))}
        </div>

        <div className="relative w-full sm:w-64">
          <Search className="w-4 h-4 text-[#827E74] absolute left-3 top-1/2 -translate-y-1/2" />
          <input
            type="text"
            placeholder="Search papers & articles..."
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            className="w-full pl-9 pr-3 py-1.5 bg-[#FAF8F5] border border-[#DDD5C5] rounded-xs text-xs text-[#0F0F0E] focus:outline-none focus:border-[#BFA272] font-sans"
          />
        </div>
      </div>

      {/* Articles Grid */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-8">
        {filteredArticles.map((article) => (
          <ResearchCard key={article.slug} {...article} />
        ))}
      </div>

      {/* Research Methodology Disclaimer */}
      <div className="bg-[#FAF8F5] border border-[#DDD5C5] rounded-xs p-6 text-xs text-[#47453F] leading-relaxed max-w-4xl mx-auto space-y-1 font-mono">
        <span className="font-semibold text-[#0F0F0E] block uppercase tracking-wider text-[11px]">
          Research Desk Disclosure:
        </span>
        <p>
          All research briefs, educational models, and comparative analyses published by Joint Bricks are intended strictly for informational and educational purposes. They do not constitute formal investment advice, legal counsel, or financial recommendations.
        </p>
      </div>

    </div>
  );
};
